name: upper-build

on:
  push:
    paths:
      - ".github/workflows/upper-build.yml"
      - "upper/**"
  workflow_dispatch: # manual

jobs:
    build:
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v4  
          - run: go version
          - uses: actions/setup-go@v5
            with:
              go-version: '1.22'
          - run: go version